modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/TheIllusiveC4/Curios/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.curios]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curios]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"