modLoader="javafml"
loaderVersion="[33,)"
license="LGPLv3"
issueTrackerURL="https://github.com/TheIllusiveC4/Curios/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.curios]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curios]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"