modLoader="javafml"
loaderVersion="[41,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/Curios/issues"
logoFile="curios_icon.png"
logoBlur=false
[[mods]]
modId="curios"
version="${file.jarVersion}"
displayName="Curios API"
displayURL="https://www.curseforge.com/minecraft/mc-mods/curios"
authors="C4"
description='''
A flexible and expandable accessory/equipment API for users and developers.
'''
[[dependencies.curios]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curios]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[modproperties.curios]
    catalogueImageIcon="curios_icon.png"